[project]
name = "book-5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy==1.26.4",
    "scipy>=1.17.0",
    "torch==2.1.2",
    "torchvision>=0.16.2",
]
